[versions]
lombok = "1.18.34"
junit = "5.10.2"
jspecify = "1.0.0"

[libraries]
lombok = { group = "org.projectlombok", name = "lombok", version.ref = "lombok" }
junit-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }

[bundles]
junit5 = [
    "junit-api",
    "junit-engine",
    "junit-params"
]